"""update

Revision ID: 64b04cb3bcf0
Revises: None
Create Date: 2016-05-17 17:15:24.624727

"""

# revision identifiers, used by Alembic.
revision = '64b04cb3bcf0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live', sa.Column('roomid', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live', 'roomid')
    ### end Alembic commands ###
